export const tasks = [
  {
    status: "IN_PROCESS",
    author: "Иванов И.И.",
    authorEdited: "Петров В.В.",
    dateCreated: "1 час назад",
    dateEdited: "1 час назад",
    _id: "6495884dee9f515ec4443a7a",
    name: "New Task Name",
    projectCode: "6495884",
    number: "1",
  },
  {
    status: "IN_PROCESS",
    author: "Иванов И.И.",
    authorEdited: "Петров В.В.",
    dateCreated: "1 час назад",
    dateEdited: "1 час назад",
    _id: "6495884dee9f515ec4443a7",
    name: "New Task Name",
    projectCode: "6495884",
    number: "2",
  },
  {
    status: "DRAFT",
    author: "Иванов И.И.",
    authorEdited: "Петров В.В.",
    dateCreated: "1 час назад",
    dateEdited: "1 час назад",
    _id: "6495884dee9f515ec4443",
    name: "New Task Name",
    projectCode: "6495884",
    number: "3",
  },
  {
    status: "DRAFT",
    author: "Иванов И.И.",
    authorEdited: "Петров В.В.",
    dateCreated: "1 час назад",
    dateEdited: "1 час назад",
    _id: "6495884dee9f515ec444",
    name: "New Task Name",
    projectCode: "6495884",
    number: "4",
  },
  {
    status: "DRAFT",
    author: "Иванов И.И.",
    authorEdited: "Петров В.В.",
    dateCreated: "1 час назад",
    dateEdited: "1 час назад",
    _id: "6495884dee9f515ec44",
    name: "New Task Name",
    projectCode: "6495884",
    number: "5",
  },
];

export const projects = [
  {
    author: "Иванов И.И.",
    authorEdited: "Петров В.В.",
    dateCreated: "1 час назад",
    dateEdited: "1 час назад",
    _id: "6495884dee9f515ec4443a7a",
    name: "New Project Name",
    code: "6495884",
  },
  {
    author: "Иванов И.И.",
    authorEdited: "Петров В.В.",
    dateCreated: "1 час назад",
    dateEdited: "1 час назад",
    _id: "6495884dee9f515ec4443a7",
    name: "New Project Name",
    code: "6495884",
  },
  {
    author: "Иванов И.И.",
    authorEdited: "Петров В.В.",
    dateCreated: "1 час назад",
    dateEdited: "1 час назад",
    _id: "6495884dee9f515ec4443",
    name: "New Project Name",
    code: "6495884",
  },
  {
    author: "Иванов И.И.",
    authorEdited: "Петров В.В.",
    dateCreated: "1 час назад",
    dateEdited: "1 час назад",
    _id: "6495884dee9f515ec444",
    name: "New Project Name",
    code: "6495884",
  },
  {
    author: "Иванов И.И.",
    authorEdited: "Петров В.В.",
    dateCreated: "1 час назад",
    dateEdited: "1 час назад",
    _id: "6495884dee9f515ec4",
    name: "New Project Name",
    code: "6495884",
  },
];
